### ISSUE TITLE
Minimum requirement is knockout@3.2.0

### ISSUE THREAD

**Issue by Nemo157** [One-com/knockout-transformations#6]
The `peerDependency` claim says that `knockout-transformations` works with any version of `knockout` from `3.0.0` up, however `indexBy` uses `ko.pureComputed` which appears to have been introduced in `3.2.0`. Failing test-case:

``` sh
npm install knockout@3.1.0 knockout-transformations@2.0.0
node -e "var ko = require('knockout'); require('knockout-transformations'); ko.observableArray([1]).indexBy(function (i) { return i; });"
```

results in

```
knockout-transformations\lib\indexBy.js:32
        var outputComputed = ko.pureComputed(this.outputObservable);
                                ^
TypeError: undefined is not a function
```

**Comment by sunesimonsen** [comment]
Thanks for noticing, I thought I had removed all the pure computed. I'll fix it tomorrow.

**Comment by Nemo157** [comment]
Thanks :)
